import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import '../styles/globals.css';

import { alegreya, roboto_slab, nunito_sans, mulish } from './fonts/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${alegreya.className} ${mulish.className} ${roboto_slab.className}`}
    >
      <body
        className={`${nunito_sans.className} flex min-h-screen w-full flex-col bg-[#222222]`}
      >
        <Navbar />
        <div className="flex-1 flex flex-col">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
